ascii_to_uppercase:
	.c00: db 0   	; None
	.c01: db 0   	; None
	.c02: db 0   	; None
	.c03: db 0   	; None
	.c04: db 0   	; None
	.c05: db 0   	; None
	.c06: db 0   	; None
	.c07: db 0   	; None
	.c08: db 0   	; None
	.c09: db 0   	; None
	.c0a: db 0   	; None
	.c0b: db 0   	; None
	.c0c: db 0   	; None
	.c0d: db 0   	; None
	.c0e: db 0   	; None
	.c0f: db 0   	; None
	.c10: db 0   	; None
	.c11: db 0   	; None
	.c12: db 0   	; None
	.c13: db 0   	; None
	.c14: db 0   	; None
	.c15: db 0   	; None
	.c16: db 0   	; None
	.c17: db 0   	; None
	.c18: db 0   	; None
	.c19: db 0   	; None
	.c1a: db 0   	; None
	.c1b: db 0   	; None
	.c1c: db 0   	; None
	.c1d: db 0   	; None
	.c1e: db 0   	; None
	.c1f: db 0   	; None
	.c20: db 0   	; None
	.c21: db 0   	; None
	.c22: db 0   	; None
	.c23: db 0   	; None
	.c24: db 0   	; None
	.c25: db 0   	; None
	.c26: db 0   	; None
	.c27: db """ 	; "
	.c28: db 0   	; None
	.c29: db 0   	; None
	.c2a: db 0   	; None
	.c2b: db 0   	; None
	.c2c: db "<" 	; <
	.c2d: db "_" 	; _
	.c2e: db ">" 	; >
	.c2f: db "?" 	; ?
	.c30: db ")" 	; )
	.c31: db "!" 	; !
	.c32: db "@" 	; @
	.c33: db "#" 	; #
	.c34: db "$" 	; $
	.c35: db "E" 	; E
	.c36: db "^" 	; ^
	.c37: db "&" 	; &
	.c38: db "*" 	; *
	.c39: db "(" 	; (
	.c3a: db 0   	; None
	.c3b: db ":" 	; :
	.c3c: db 0   	; None
	.c3d: db "+" 	; +
	.c3e: db 0   	; None
	.c3f: db 0   	; None
	.c40: db 0   	; None
	.c41: db 0   	; None
	.c42: db 0   	; None
	.c43: db 0   	; None
	.c44: db 0   	; None
	.c45: db 0   	; None
	.c46: db 0   	; None
	.c47: db 0   	; None
	.c48: db 0   	; None
	.c49: db 0   	; None
	.c4a: db 0   	; None
	.c4b: db 0   	; None
	.c4c: db 0   	; None
	.c4d: db 0   	; None
	.c4e: db 0   	; None
	.c4f: db 0   	; None
	.c50: db 0   	; None
	.c51: db 0   	; None
	.c52: db 0   	; None
	.c53: db 0   	; None
	.c54: db 0   	; None
	.c55: db 0   	; None
	.c56: db 0   	; None
	.c57: db 0   	; None
	.c58: db 0   	; None
	.c59: db 0   	; None
	.c5a: db 0   	; None
	.c5b: db "{" 	; {
	.c5c: db "|" 	; |
	.c5d: db "}" 	; }
	.c5e: db 0   	; None
	.c5f: db 0   	; None
	.c60: db "~" 	; ~
	.c61: db "A" 	; A
	.c62: db "B" 	; B
	.c63: db "C" 	; C
	.c64: db "D" 	; D
	.c65: db "E" 	; E
	.c66: db "F" 	; F
	.c67: db "G" 	; G
	.c68: db "H" 	; H
	.c69: db "I" 	; I
	.c6a: db "J" 	; J
	.c6b: db "K" 	; K
	.c6c: db "L" 	; L
	.c6d: db "M" 	; M
	.c6e: db "N" 	; N
	.c6f: db "O" 	; O
	.c70: db "P" 	; P
	.c71: db "Q" 	; Q
	.c72: db "R" 	; R
	.c73: db "S" 	; S
	.c74: db "T" 	; T
	.c75: db "U" 	; U
	.c76: db "V" 	; V
	.c77: db "W" 	; W
	.c78: db "X" 	; X
	.c79: db "Y" 	; Y
	.c7a: db "Z" 	; Z
	.c7b: db 0   	; None
	.c7c: db 0   	; None
	.c7d: db 0   	; None
	.c7e: db 0   	; None
	.c7f: db 0   	; None
	.c80: db 0   	; None
	.c81: db 0   	; None
	.c82: db 0   	; None
	.c83: db 0   	; None
	.c84: db 0   	; None
	.c85: db 0   	; None
	.c86: db 0   	; None
	.c87: db 0   	; None
	.c88: db 0   	; None
	.c89: db 0   	; None
	.c8a: db 0   	; None
	.c8b: db 0   	; None
	.c8c: db 0   	; None
	.c8d: db 0   	; None
	.c8e: db 0   	; None
	.c8f: db 0   	; None
	.c90: db 0   	; None
	.c91: db 0   	; None
	.c92: db 0   	; None
	.c93: db 0   	; None
	.c94: db 0   	; None
	.c95: db 0   	; None
	.c96: db 0   	; None
	.c97: db 0   	; None
	.c98: db 0   	; None
	.c99: db 0   	; None
	.c9a: db 0   	; None
	.c9b: db 0   	; None
	.c9c: db 0   	; None
	.c9d: db 0   	; None
	.c9e: db 0   	; None
	.c9f: db 0   	; None
	.ca0: db 0   	; None
	.ca1: db 0   	; None
	.ca2: db 0   	; None
	.ca3: db 0   	; None
	.ca4: db 0   	; None
	.ca5: db 0   	; None
	.ca6: db 0   	; None
	.ca7: db 0   	; None
	.ca8: db 0   	; None
	.ca9: db 0   	; None
	.caa: db 0   	; None
	.cab: db 0   	; None
	.cac: db 0   	; None
	.cad: db 0   	; None
	.cae: db 0   	; None
	.caf: db 0   	; None
	.cb0: db 0   	; None
	.cb1: db 0   	; None
	.cb2: db 0   	; None
	.cb3: db 0   	; None
	.cb4: db 0   	; None
	.cb5: db 0   	; None
	.cb6: db 0   	; None
	.cb7: db 0   	; None
	.cb8: db 0   	; None
	.cb9: db 0   	; None
	.cba: db 0   	; None
	.cbb: db 0   	; None
	.cbc: db 0   	; None
	.cbd: db 0   	; None
	.cbe: db 0   	; None
	.cbf: db 0   	; None
	.cc0: db 0   	; None
	.cc1: db 0   	; None
	.cc2: db 0   	; None
	.cc3: db 0   	; None
	.cc4: db 0   	; None
	.cc5: db 0   	; None
	.cc6: db 0   	; None
	.cc7: db 0   	; None
	.cc8: db 0   	; None
	.cc9: db 0   	; None
	.cca: db 0   	; None
	.ccb: db 0   	; None
	.ccc: db 0   	; None
	.ccd: db 0   	; None
	.cce: db 0   	; None
	.ccf: db 0   	; None
	.cd0: db 0   	; None
	.cd1: db 0   	; None
	.cd2: db 0   	; None
	.cd3: db 0   	; None
	.cd4: db 0   	; None
	.cd5: db 0   	; None
	.cd6: db 0   	; None
	.cd7: db 0   	; None
	.cd8: db 0   	; None
	.cd9: db 0   	; None
	.cda: db 0   	; None
	.cdb: db 0   	; None
	.cdc: db 0   	; None
	.cdd: db 0   	; None
	.cde: db 0   	; None
	.cdf: db 0   	; None
	.ce0: db 0   	; None
	.ce1: db 0   	; None
	.ce2: db 0   	; None
	.ce3: db 0   	; None
	.ce4: db 0   	; None
	.ce5: db 0   	; None
	.ce6: db 0   	; None
	.ce7: db 0   	; None
	.ce8: db 0   	; None
	.ce9: db 0   	; None
	.cea: db 0   	; None
	.ceb: db 0   	; None
	.cec: db 0   	; None
	.ced: db 0   	; None
	.cee: db 0   	; None
	.cef: db 0   	; None
	.cf0: db 0   	; None
	.cf1: db 0   	; None
	.cf2: db 0   	; None
	.cf3: db 0   	; None
	.cf4: db 0   	; None
	.cf5: db 0   	; None
	.cf6: db 0   	; None
	.cf7: db 0   	; None
	.cf8: db 0   	; None
	.cf9: db 0   	; None
	.cfa: db 0   	; None
	.cfb: db 0   	; None
	.cfc: db 0   	; None
	.cfd: db 0   	; None
	.cfe: db 0   	; None
	.cff: db 0   	; None
